### ISSUE TITLE
Final To-Do's

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/fee-lab-to-nwb#32]
Some final To-Do's, leaving here as a mental note

- [x] polish version pinning of upstream packages so it doesn't spontaneously break at some point
- [ ] copy/paste some nicer issue forms
- [x] utilize `neuroconv[...]` minimal dependencies for convenience (P.S. does this play well with version specificity? that is, `neuroconv[spikeglx]<=0.2.0`?)
- [x] Add documentation reminding people to manually copy/paste usage scripts when installing from `pip` (scripts will technically be wherever their `pip` installs site packages, but that's not a typical working directory...)

As far as data goes...
- [x] *maybe* include waveforms. Might need to discuss if they want/need this for aim 3

**Comment by CodyCBakerPhD** [comment]
We can probably call this good now, do you agree @weiglszonja?
